#! /bin/sh
# If refreshing bspwm, remove all previous rules to prevent doubling up.
bspc rule -r "*"

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config ignore_ewmh_focus    true

$HOME/.config/polybar/launch.sh
